name: CI

on: push

jobs:
  job1_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Build application
        working-directory: frontend
        run: npm run build